-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 10:20:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webcrawler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webcrawler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webcrawler` ;
USE `webcrawler` ;

-- -----------------------------------------------------
-- Table `webcrawler`.`Scans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`Scans` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`Scans` (
  `scan_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `start_timestamp` DATETIME NULL,
  `end_timestamp` DATETIME NULL,
  `seed_url` TEXT NULL,
  `search_fqdn_re` TEXT NULL,
  `sub_path_re` TEXT NULL,
  PRIMARY KEY (`scan_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `scan_id_UNIQUE` (`scan_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcrawler`.`FoundURLs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`FoundURLs` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`FoundURLs` (
  `url_id` INT NOT NULL AUTO_INCREMENT,
  `scan_id` INT NOT NULL,
  `url_hash` VARCHAR(64) NOT NULL,
  `url_text` TEXT NULL,
  `root_stem` TEXT NULL,
  `fqdn` TEXT NULL,
  `is_crawled` TINYINT NULL,
  `is_blacklisted` TINYINT NULL,
  `redirect_parent_url_id` INT NULL,
  `status_code` VARCHAR(3) NULL,
  `content_type` VARCHAR(128) NULL,
  `page_title` TEXT NULL,
  `created_timestamp` DATETIME NULL,
  `crawled_timestamp` DATETIME NULL,
  PRIMARY KEY (`url_id`),
  UNIQUE INDEX `UNIQUE-scan_id-url_hash` (`scan_id` ASC, `url_hash` ASC),
  INDEX `INDEX-scan_id-url_hash` (`scan_id` ASC, `url_hash` ASC),
  CONSTRAINT `fk_URLs_PK`
    FOREIGN KEY (`scan_id`)
    REFERENCES `webcrawler`.`Scans` (`scan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcrawler`.`Backlinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`Backlinks` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`Backlinks` (
  `url_id` INT NOT NULL,
  `backlink_url_id` INT NOT NULL,
  `backlink_timestamp` DATETIME NULL,
  INDEX `fk-Backlinks-backlink_url_id_idx` (`backlink_url_id` ASC),
  CONSTRAINT `fk-Backlinks-url_id`
    FOREIGN KEY (`url_id`)
    REFERENCES `webcrawler`.`FoundURLs` (`url_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-Backlinks-backlink_url_id`
    FOREIGN KEY (`backlink_url_id`)
    REFERENCES `webcrawler`.`FoundURLs` (`url_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcrawler`.`PageLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`PageLinks` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`PageLinks` (
  `url_id` INT NOT NULL,
  `link` TEXT NOT NULL,
  `linktext` TEXT NULL,
  INDEX `fk-PageLinks-url_id_idx` (`url_id` ASC),
  CONSTRAINT `fk-PageLinks-url_id`
    FOREIGN KEY (`url_id`)
    REFERENCES `webcrawler`.`FoundURLs` (`url_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcrawler`.`ScanErrors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`ScanErrors` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`ScanErrors` (
  `url_id` INT NOT NULL,
  `error_text` TEXT NULL,
  `error_timestamp` DATETIME NULL,
  CONSTRAINT `fk_ScanErrors-url_id`
    FOREIGN KEY (`url_id`)
    REFERENCES `webcrawler`.`FoundURLs` (`url_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcrawler`.`ScanRoots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`ScanRoots` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`ScanRoots` (
  `scan_id` INT NOT NULL,
  `fqdn` VARCHAR(512) NOT NULL,
  `port` VARCHAR(5) NULL,
  UNIQUE INDEX `idx_ScanRoots_UNIQUE` (`scan_id` ASC, `fqdn` ASC, `port` ASC),
  CONSTRAINT `fk_ScanRoots-scan_id`
    FOREIGN KEY (`scan_id`)
    REFERENCES `webcrawler`.`Scans` (`scan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcrawler`.`ScanBlackLists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcrawler`.`ScanBlackLists` ;

CREATE TABLE IF NOT EXISTS `webcrawler`.`ScanBlackLists` (
  `scan_id` INT NOT NULL,
  `fqdn` VARCHAR(512) NOT NULL,
  `path` VARCHAR(2048) NULL,
  `scheme` VARCHAR(2048) NULL,
  `netloc` VARCHAR(2048) NULL,
  CONSTRAINT `fk_ScanBlackLists-scan_id`
    FOREIGN KEY (`scan_id`)
    REFERENCES `webcrawler`.`Scans` (`scan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
